### ISSUE TITLE
Error when retrieving album list

### ISSUE THREAD

**Issue by envas** [inetis-ch/oc-GooglePhotos-plugin#18]
I installed and configured the plugin (on localhost), and I could successfully log in to Google Photos. When opening a page with the component `googlePhotosAlbums`, I got the error

```
Undefined property: stdClass::$mediaItemsCount
~/plugins/inetis/googlephotos/picasawebdata/elements/Album.php line 36
```

Any idea?

**Comment by envas** [comment]
I just discovered that happened when an album was empty. This exception should be catched, so in my opinion it's a bug.

**Comment by Fl0Cri** [comment]
This is indeed a bug, thanks for reporting it.

Version 1.5.1 includes some fixes to handle empty albums properly.
