### ISSUE TITLE
Error on single album component

### ISSUE THREAD

**Issue by bjlatta** [inetis-ch/oc-GooglePhotos-plugin#7]
Getting the following error on the admin page when I click on the component. I cannot add the album ID, because of the error.
"Cannot use object of type Inetis\GooglePhotos\PicasaWebData\Elements\Album as array" on line 101 /var/www/****/public_html/plugins/inetis/googlephotos/components/GooglePhotosAlbum.php . "*****" is my website folder, hidden here because I do not want to make it public. The gallery page is working showing my albums.

**Comment by Fl0Cri** [comment]
Thanks for reporting this.
I've made a PR to fix the issue, we will make a release after the week-end.

So if you want to get fixed right now you can just replace line 101 of this file https://github.com/inetis-ch/oc-GooglePhotos-plugin/blob/master/components/GooglePhotosAlbum.php#L101 by this:
```PHP
return ['id:' . $item->albumId => $item->albumTitle];
```

**Comment by Fl0Cri** [comment]
Fixed in release 1.2.2
